name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Demo LS on VPS
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd public_html/travaux/wr505d
          git clone git@github.com:enzocosson/wr505-app-vuejs.git
          cd wr505-app-vuejs
          git pull
          composer install
          php bin/console c:c
