name: Déploiement vers mon VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v2

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Installer les dépendances
        run: npm install

      - name: Construire
        run: npm run build

      - name: 📂 Uploader SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: "./dist/"
          remoteDir: "/home/mmi21e03/public_html/vue-js/"
